name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Oder dein Haupt-Branch, z.B. "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Erlaubnis, um Dateien in den gh-pages Branch zu schreiben

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install js-yaml # Laut deiner package.json
          # Füge hier weitere Abhängigkeiten hinzu, falls du welche hast

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
